site_name: PolyLaue Documentation
site_url: https://polylaue.github.io
repo_url: https://github.com/polylaue/polylaue
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences
nav:
  - index.md
  - getting-started.md
  - projects.md
  - viewing.md
  - identification.md
  - point-picking.md
  - reflections.md
  - mapping.md
  - saving-data.md
  - algorithms.md
  - calibration.md
  - structure-types.md
  - references.md
