site_name: PolyLaue Documentation
site_url: https://polylaue.github.io
repo_url: https://github.com/polylaue/polylaue
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.superfences
nav:
  - index.md
  - algorithms.md
  - references.md
